export default {
    button: 'xl-button',
    icon: 'i',
    slider: 'xl-slider',
    rate: 'xl-rate',
    upload: 'fc-elm-upload',
    cascader: 'xl-cascader',
    colorPicker: 'xl-color-picker',
    timePicker: 'xl-time-picker',
    datePicker: 'xl-date-picker',
    'switch': 'xl-switch',
    select: 'fc-elm-select',
    checkbox: 'fc-elm-checkbox',
    radio: 'fc-elm-radio',
    inputNumber: 'xl-input-number',
    input: 'xl-input',
    formItem: 'xl-form-item',
    form: 'xl-form',
    frame: 'fc-elm-frame',
    col: 'xl-col',
    row: 'xl-row',
    tree: 'fc-elm-tree',
    autoComplete: 'xl-autocomplete',
    group: 'fc-elm-group',
}
